<!DOCTYPE html>
<html>
<head>
    <title>Studio of Contemporary Creation</title>
    <link rel="stylesheet" href="/styles/site.min.css"/>
    <link href='http://fonts.googleapis.com/css?family=Ubuntu:400,300' rel='stylesheet' type='text/css'>
    <link href='http://awebfont.ir/css?id=1062' rel='stylesheet' type='text/css'>
</head>
<body>
<header>
    <img class="img_area" onclick="home_button()" src="/images/logo.png">
    <label>HOME</label>
</header>
<div id="scc">
    <img src="/images/scc.png">
</div>
<section id="programs">
    <div class="icon"><img src="/images/programs.png" usemap="#programs_map"><label id="programs_label">Programs</label></div>
    <div class="content">
    	<div class="program_item">
    		<div class="title">
    			<label class="en">Exhibitions</label>
    			<label class="fa">نمایشگاه ها</label>
    			<a class="lang_change" onclick="change_lang(this)">فا</a>
    		</div>
    		<div class="text">
    			<p class="en">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis</p>
    			<p class="fa">(فارسی)Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis</p>
            </div>
    	</div>
    	<div class="program_item">
    		<div class="title">
    			<label class="en">Residency</label>
    			<label class="fa">اقامت</label>
    			<a class="lang_change" onclick="change_lang(this)">فا</a>
    		</div>
    		<div class="text">
    			<p class="en">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis</p>
    			<p class="fa">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis</p>
            </div>
    	</div>
    	<div class="program_item">
    		<div class="title">
    			<label class="en">Residency</label>
    			<label class="fa">اقامت</label>
    			<a class="lang_change" onclick="change_lang(this)">فا</a>
    		</div>
    		<div class="text">
    			<p class="en">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis</p>
    			<p class="fa">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis</p>
            </div>
    	</div>
    	<div class="program_item">
    		<div class="title">
    			<label class="en">Residency</label>
    			<label class="fa">اقامت</label>
    			<a class="lang_change" onclick="change_lang(this)">فا</a>
    		</div>
    		<div class="text">
    			<p class="en">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis</p>
    			<p class="fa">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis</p>
            </div>
    	</div>
    	<div class="program_item">
    		<div class="title">
    			<label class="en">Residency</label>
    			<label class="fa">اقامت</label>
    			<a class="lang_change" onclick="change_lang(this)">فا</a>
    		</div>
    		<div class="text">
    			<p class="en">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis</p>
    			<p class="fa">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis</p>
            </div>
    	</div>    	    	    	    	
    </div>
    <map name="programs_map">
        <area class="img_area" shape="poly" coords="297,74,557,310,359,544,86,281,297,74" onmouseover="label_mouseover('programs')" onmouseout="label_mouseout('programs')" onclick="transition('programs')" >
    </map>
</section>
<section id="contacts">
    <div class="icon"><img src="/images/contacts.png" usemap="#contacts_map"><label id="contacts_label">Contacts</label></div>
    <div class="content">
        <div class="contacts_eng">
            <p>No. 14, Sa'di Alley (8), Abouzar St.<br />Isfahan, Iran<br /><br />Tel:983132348812<br />Fax:983132348813<br /><br />E-mail : info@s-cc.org</p>
        </div>
        <div class="contacts_fa fa">
			<p>خیابان ابوذر، کوچه سعدی، پلاک ۱۴<br />ایران، اصفهان<br /><br />تلفن:۹۸۳۱۳۲۳۴۸۸۱۲<br />دورنگار:۹۸۳۱۳۲۳۴۸۸۱۳</p>
        </div>
    </div>
    <map name="contacts_map">
        <area class="img_area" shape="poly" coords="40,55,103,54,107,197,55,197,46,55" onmouseover="label_mouseover('contacts')" onmouseout="label_mouseout('contacts')" onclick="transition('contacts')" >
    </map>
</section>
<section id="publishing">
    <div class="icon"><img src="/images/publishing.png"></div>
    <div class="content"></div>
</section>
<section id="events">
    <div class="icon"><img src="/images/events.png"></div>
    <div class="content"></div>
</section>
<section id="news">
    <div class="icon"><img src="/images/news.png"></div>
    <div class="content"></div>
</section>
<section id="residency">
    <div class="icon"><img src="/images/residency.png" usemap="#residency_map"><label id="residency_label">Residency</label></div>
    <div class="content"></div>
    <map name="residency_map">
        <area class="img_area" shape="poly" coords="53,49,347,41,354,281,58,290,53,49" onmouseover="label_mouseover('residency')" onmouseout="label_mouseout('residency')" onclick="transition('residency')" >
    </map>
</section>
<section id="about">
    <div class="icon"><img src="/images/about.png" usemap="#about_map"><label id="about_label">About</label></div>
    <div class="content bezier_transition">
        <div class="about_carousel"></div>
        <div class="about_text"><h4>Studio of Contemporary Creation</h4><p class="text">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis..</p></div>
    </div>
    <map name="about_map">
        <area class="img_area" shape="poly" coords="128,15,246,40,222,158,104,137,128,15" onmouseover="label_mouseover('about')" onmouseout="label_mouseout('about')" onclick="transition('about')" >
    </map>
</section>
<script src="/js/lib/jquery/jquery-1.11.1.min.js" type="text/javascript"></script>
<script src="/js/scc_script.js" type="text/javascript"></script>

</body>

</html>
